### ISSUE TITLE
Create Minio deployment

### ISSUE THREAD

**Issue by faisaladnanpeltops** [k8-proxy/p-k8-jmeter-test-engine-v1#4]
Create scripts that does the following:

- Deploy Minio
- Create buckets
  - input queue
  - output queue
  - govUk
- Populate govUk bucket with files from https://k8-mass-download.s3.eu-west-2.amazonaws.com/gov_Files.zip

There are 2 kind of scripts:
1. docker compose for local development
2. k8s manifest for staging and production environments

**Comment by NadHodeGW** [comment]
No longer required as done in issue #2
