### ISSUE TITLE
Controlling JMeter Pod 

### ISSUE THREAD

**Issue by faisaladnanpeltops** [k8-proxy/p-k8-jmeter-test-engine-v1#5]
Create a script that:
1. run a JMeter pod for a certain input files
2. listen to a new file event and run a JMeter pod 
3. process all files in a minio bucket

**Comment by ggrig** [comment]
Hi Faisal
Do we expect this to be deployed in the kubernetes-the-hard-way cluster you have shared the access?
Or do we expect it to be in AWS EC2 that you have requested the access for the team (https://glasswallsolu-qbp1117.slack.com/archives/C01ARBKG124/p1600898734007400)?

**Comment by faisaladnanpeltops** [comment]
@ggrig in AWS EC2. The external cluster is a sandbox for experiments.

**Comment by ggrig** [comment]
https://github.com/k8-proxy/p-k8-jmeter-test-engine-v1/tree/master/upwork-devs/MaNe2020/docker-icap-jmeter-testdata/jmeter-c-icap

**Comment by ggrig** [comment]
Following up on the task:
- JMeter results should be transferred to Minio
- Ability to scale it up to as many pods as the cluster allows
- Process customized JMX files
