### ISSUE TITLE
deploy cloud icap server

### ISSUE THREAD

**Issue by faisaladnanpeltops** [k8-proxy/p-k8-jmeter-test-engine-v1#7]
this is to be taken by Pranay

**Comment by dpatel7** [comment]
@faisaladnanpeltops Please update more details about this task

**Comment by faisaladnanpeltops** [comment]
not an issue

**Comment by pranaysahith** [comment]
As per @dpatel7  this issue is not required, as we are using icap server which is deployed on Azure.
