### ISSUE TITLE
son ha: Execution synchronize about jmeter vs direct commands to ICAP server

### ISSUE THREAD

**Issue by faisaladnanpeltops** [k8-proxy/p-k8-jmeter-test-engine-v1#8]
this is to taken by son ha

**Comment by dpatel7** [comment]
@faisaladnanpeltops any progress from son ha?

**Comment by hongson1981** [comment]
@dpatel7  I done this task and also send analyze document to @faisaladnanpeltops and @NadHodeGW , please refer attached file
[Performance test execution analyzation for Glasswall ICAP server rebuild.docx](https://github.com/k8-proxy/p-k8-jmeter-test-engine-v1/files/5299080/Performance.test.execution.analyzation.for.Glasswall.ICAP.server.rebuild.docx)

**Comment by dpatel7** [comment]
@faisaladnanpeltops can you explain what we discuss about profiles and load pattern to son-ha
